[
    .[]|
    (
        .formula_names[],.cask_tokens[]
    )
]|
del(.[]|
    select(
        .==(
            "cblecker/tap/hypershift",
            "cblecker/tap/kubectl-dev_tool",
            "cblecker/tap/ocm-backplane"
        )
    )
)
